<?php

/**
 * BaseRiskBuilder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $form_name
 * @property string $form_instructions
 * @property string $mitigation_low_message
 * @property string $mitigation_low_instructions
 * @property integer $mitigation_low_min
 * @property integer $mitigation_low_max
 * @property boolean $mitigation_low_notify
 * @property string $mitigation_medium_message
 * @property string $mitigation_medium_instructions
 * @property integer $mitigation_medium_min
 * @property integer $mitigation_medium_max
 * @property boolean $mitigation_medium_notify
 * @property boolean $mitigation_medium_require_details
 * @property string $mitigation_high_message
 * @property string $mitigation_high_instructions
 * @property integer $mitigation_high_min
 * @property integer $mitigation_high_max
 * @property boolean $mitigation_high_notify
 * @property boolean $mitigation_high_prevent_flight
 * @property Doctrine_Collection $FlightInformationField
 * @property Doctrine_Collection $RiskBuilder
 * 
 * @method string              getFormName()                          Returns the current record's "form_name" value
 * @method string              getFormInstructions()                  Returns the current record's "form_instructions" value
 * @method string              getMitigationLowMessage()              Returns the current record's "mitigation_low_message" value
 * @method string              getMitigationLowInstructions()         Returns the current record's "mitigation_low_instructions" value
 * @method integer             getMitigationLowMin()                  Returns the current record's "mitigation_low_min" value
 * @method integer             getMitigationLowMax()                  Returns the current record's "mitigation_low_max" value
 * @method boolean             getMitigationLowNotify()               Returns the current record's "mitigation_low_notify" value
 * @method string              getMitigationMediumMessage()           Returns the current record's "mitigation_medium_message" value
 * @method string              getMitigationMediumInstructions()      Returns the current record's "mitigation_medium_instructions" value
 * @method integer             getMitigationMediumMin()               Returns the current record's "mitigation_medium_min" value
 * @method integer             getMitigationMediumMax()               Returns the current record's "mitigation_medium_max" value
 * @method boolean             getMitigationMediumNotify()            Returns the current record's "mitigation_medium_notify" value
 * @method boolean             getMitigationMediumRequireDetails()    Returns the current record's "mitigation_medium_require_details" value
 * @method string              getMitigationHighMessage()             Returns the current record's "mitigation_high_message" value
 * @method string              getMitigationHighInstructions()        Returns the current record's "mitigation_high_instructions" value
 * @method integer             getMitigationHighMin()                 Returns the current record's "mitigation_high_min" value
 * @method integer             getMitigationHighMax()                 Returns the current record's "mitigation_high_max" value
 * @method boolean             getMitigationHighNotify()              Returns the current record's "mitigation_high_notify" value
 * @method boolean             getMitigationHighPreventFlight()       Returns the current record's "mitigation_high_prevent_flight" value
 * @method Doctrine_Collection getFlightInformationField()            Returns the current record's "FlightInformationField" collection
 * @method Doctrine_Collection getRiskBuilder()                       Returns the current record's "RiskBuilder" collection
 * @method RiskBuilder         setFormName()                          Sets the current record's "form_name" value
 * @method RiskBuilder         setFormInstructions()                  Sets the current record's "form_instructions" value
 * @method RiskBuilder         setMitigationLowMessage()              Sets the current record's "mitigation_low_message" value
 * @method RiskBuilder         setMitigationLowInstructions()         Sets the current record's "mitigation_low_instructions" value
 * @method RiskBuilder         setMitigationLowMin()                  Sets the current record's "mitigation_low_min" value
 * @method RiskBuilder         setMitigationLowMax()                  Sets the current record's "mitigation_low_max" value
 * @method RiskBuilder         setMitigationLowNotify()               Sets the current record's "mitigation_low_notify" value
 * @method RiskBuilder         setMitigationMediumMessage()           Sets the current record's "mitigation_medium_message" value
 * @method RiskBuilder         setMitigationMediumInstructions()      Sets the current record's "mitigation_medium_instructions" value
 * @method RiskBuilder         setMitigationMediumMin()               Sets the current record's "mitigation_medium_min" value
 * @method RiskBuilder         setMitigationMediumMax()               Sets the current record's "mitigation_medium_max" value
 * @method RiskBuilder         setMitigationMediumNotify()            Sets the current record's "mitigation_medium_notify" value
 * @method RiskBuilder         setMitigationMediumRequireDetails()    Sets the current record's "mitigation_medium_require_details" value
 * @method RiskBuilder         setMitigationHighMessage()             Sets the current record's "mitigation_high_message" value
 * @method RiskBuilder         setMitigationHighInstructions()        Sets the current record's "mitigation_high_instructions" value
 * @method RiskBuilder         setMitigationHighMin()                 Sets the current record's "mitigation_high_min" value
 * @method RiskBuilder         setMitigationHighMax()                 Sets the current record's "mitigation_high_max" value
 * @method RiskBuilder         setMitigationHighNotify()              Sets the current record's "mitigation_high_notify" value
 * @method RiskBuilder         setMitigationHighPreventFlight()       Sets the current record's "mitigation_high_prevent_flight" value
 * @method RiskBuilder         setFlightInformationField()            Sets the current record's "FlightInformationField" collection
 * @method RiskBuilder         setRiskBuilder()                       Sets the current record's "RiskBuilder" collection
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRiskBuilder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('risk_builder');
        $this->hasColumn('form_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('form_instructions', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mitigation_low_message', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mitigation_low_instructions', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mitigation_low_min', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('mitigation_low_max', 'integer', null, array(
             'type' => 'integer',
             'default' => 14,
             ));
        $this->hasColumn('mitigation_low_notify', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('mitigation_medium_message', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mitigation_medium_instructions', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mitigation_medium_min', 'integer', null, array(
             'type' => 'integer',
             'default' => 15,
             ));
        $this->hasColumn('mitigation_medium_max', 'integer', null, array(
             'type' => 'integer',
             'default' => 24,
             ));
        $this->hasColumn('mitigation_medium_notify', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('mitigation_medium_require_details', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('mitigation_high_message', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mitigation_high_instructions', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mitigation_high_min', 'integer', null, array(
             'type' => 'integer',
             'default' => 25,
             ));
        $this->hasColumn('mitigation_high_max', 'integer', null, array(
             'type' => 'integer',
             'default' => 50,
             ));
        $this->hasColumn('mitigation_high_notify', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('mitigation_high_prevent_flight', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FlightInformationField', array(
             'local' => 'id',
             'foreign' => 'risk_builder_id'));

        $this->hasMany('RiskFactorField as RiskBuilder', array(
             'local' => 'id',
             'foreign' => 'risk_builder_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}