<?php

/**
 * BaseFlight
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $account_id
 * @property integer $plane_id
 * @property integer $pic_id
 * @property integer $sic_id
 * @property varchar $trip_number
 * @property varchar $airport_from
 * @property varchar $airport_to
 * @property datetime $departure_date
 * @property integer $risk_factor_sum
 * @property integer $mitigation_sum
 * @property text $info
 * @property boolean $completed
 * @property Account $Account
 * @property Plane $Plane
 * @property sfGuardUser $PIC
 * @property sfGuardUser $SIC
 * 
 * @method integer     getAccountId()       Returns the current record's "account_id" value
 * @method integer     getPlaneId()         Returns the current record's "plane_id" value
 * @method integer     getPicId()           Returns the current record's "pic_id" value
 * @method integer     getSicId()           Returns the current record's "sic_id" value
 * @method varchar     getTripNumber()      Returns the current record's "trip_number" value
 * @method varchar     getAirportFrom()     Returns the current record's "airport_from" value
 * @method varchar     getAirportTo()       Returns the current record's "airport_to" value
 * @method datetime    getDepartureDate()   Returns the current record's "departure_date" value
 * @method integer     getRiskFactorSum()   Returns the current record's "risk_factor_sum" value
 * @method integer     getMitigationSum()   Returns the current record's "mitigation_sum" value
 * @method text        getInfo()            Returns the current record's "info" value
 * @method boolean     getCompleted()       Returns the current record's "completed" value
 * @method Account     getAccount()         Returns the current record's "Account" value
 * @method Plane       getPlane()           Returns the current record's "Plane" value
 * @method sfGuardUser getPIC()             Returns the current record's "PIC" value
 * @method sfGuardUser getSIC()             Returns the current record's "SIC" value
 * @method Flight      setAccountId()       Sets the current record's "account_id" value
 * @method Flight      setPlaneId()         Sets the current record's "plane_id" value
 * @method Flight      setPicId()           Sets the current record's "pic_id" value
 * @method Flight      setSicId()           Sets the current record's "sic_id" value
 * @method Flight      setTripNumber()      Sets the current record's "trip_number" value
 * @method Flight      setAirportFrom()     Sets the current record's "airport_from" value
 * @method Flight      setAirportTo()       Sets the current record's "airport_to" value
 * @method Flight      setDepartureDate()   Sets the current record's "departure_date" value
 * @method Flight      setRiskFactorSum()   Sets the current record's "risk_factor_sum" value
 * @method Flight      setMitigationSum()   Sets the current record's "mitigation_sum" value
 * @method Flight      setInfo()            Sets the current record's "info" value
 * @method Flight      setCompleted()       Sets the current record's "completed" value
 * @method Flight      setAccount()         Sets the current record's "Account" value
 * @method Flight      setPlane()           Sets the current record's "Plane" value
 * @method Flight      setPIC()             Sets the current record's "PIC" value
 * @method Flight      setSIC()             Sets the current record's "SIC" value
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFlight extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('flight');
        $this->hasColumn('account_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('plane_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pic_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sic_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('trip_number', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('airport_from', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('airport_to', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('departure_date', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('risk_factor_sum', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mitigation_sum', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('info', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('completed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Plane', array(
             'local' => 'plane_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as PIC', array(
             'local' => 'pic_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as SIC', array(
             'local' => 'sic_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}