<?php

/**
 * BaseResponseOptionField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $risk_factor_id
 * @property string $response_text
 * @property integer $response_value
 * @property string $note
 * @property RiskFactorField $RiskFactorField
 * 
 * @method integer             getRiskFactorId()    Returns the current record's "risk_factor_id" value
 * @method string              getResponseText()    Returns the current record's "response_text" value
 * @method integer             getResponseValue()   Returns the current record's "response_value" value
 * @method string              getNote()            Returns the current record's "note" value
 * @method RiskFactorField     getRiskFactorField() Returns the current record's "RiskFactorField" value
 * @method ResponseOptionField setRiskFactorId()    Sets the current record's "risk_factor_id" value
 * @method ResponseOptionField setResponseText()    Sets the current record's "response_text" value
 * @method ResponseOptionField setResponseValue()   Sets the current record's "response_value" value
 * @method ResponseOptionField setNote()            Sets the current record's "note" value
 * @method ResponseOptionField setRiskFactorField() Sets the current record's "RiskFactorField" value
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResponseOptionField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('response_option_field');
        $this->hasColumn('risk_factor_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('response_text', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('response_value', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RiskFactorField', array(
             'local' => 'risk_factor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}