<?php

/**
 * BaseAirport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $city
 * @property string $country
 * @property string $IATA_FAA
 * @property string $ICAO
 * @property float $latitude
 * @property float $longitude
 * @property integer $altitude
 * @property integer $timezone
 * @property enum $DST
 * @property Doctrine_Collection $Flight
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method string              getCity()      Returns the current record's "city" value
 * @method string              getCountry()   Returns the current record's "country" value
 * @method string              getIATAFAA()   Returns the current record's "IATA_FAA" value
 * @method string              getICAO()      Returns the current record's "ICAO" value
 * @method float               getLatitude()  Returns the current record's "latitude" value
 * @method float               getLongitude() Returns the current record's "longitude" value
 * @method integer             getAltitude()  Returns the current record's "altitude" value
 * @method integer             getTimezone()  Returns the current record's "timezone" value
 * @method enum                getDST()       Returns the current record's "DST" value
 * @method Doctrine_Collection getFlight()    Returns the current record's "Flight" collection
 * @method Airport             setName()      Sets the current record's "name" value
 * @method Airport             setCity()      Sets the current record's "city" value
 * @method Airport             setCountry()   Sets the current record's "country" value
 * @method Airport             setIATAFAA()   Sets the current record's "IATA_FAA" value
 * @method Airport             setICAO()      Sets the current record's "ICAO" value
 * @method Airport             setLatitude()  Sets the current record's "latitude" value
 * @method Airport             setLongitude() Sets the current record's "longitude" value
 * @method Airport             setAltitude()  Sets the current record's "altitude" value
 * @method Airport             setTimezone()  Sets the current record's "timezone" value
 * @method Airport             setDST()       Sets the current record's "DST" value
 * @method Airport             setFlight()    Sets the current record's "Flight" collection
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAirport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('airport');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('IATA_FAA', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
        $this->hasColumn('ICAO', 'string', 4, array(
             'type' => 'string',
             'length' => 4,
             ));
        $this->hasColumn('latitude', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('longitude', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('altitude', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('timezone', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('DST', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'E',
              1 => 'A',
              2 => 'S',
              3 => 'O',
              4 => 'Z',
              5 => 'N',
              6 => 'U',
             ),
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Flight', array(
             'local' => 'id',
             'foreign' => 'airport_from_id'));
    }
}