<?php

/**
 * BaseAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $title
 * @property varchar $photo
 * @property varchar $chief_pilot_email
 * @property varchar $chief_pilot_name
 * @property integer $managed_by_id
 * @property Doctrine_Collection $Planes
 * @property Doctrine_Collection $Users
 * @property sfGuardUser $Manager
 * @property Doctrine_Collection $RiskBuilders
 * @property Doctrine_Collection $AccountPlane
 * @property Doctrine_Collection $UserAccount
 * 
 * @method varchar             getTitle()             Returns the current record's "title" value
 * @method varchar             getPhoto()             Returns the current record's "photo" value
 * @method varchar             getChiefPilotEmail()   Returns the current record's "chief_pilot_email" value
 * @method varchar             getChiefPilotName()    Returns the current record's "chief_pilot_name" value
 * @method integer             getManagedById()       Returns the current record's "managed_by_id" value
 * @method Doctrine_Collection getPlanes()            Returns the current record's "Planes" collection
 * @method Doctrine_Collection getUsers()             Returns the current record's "Users" collection
 * @method sfGuardUser         getManager()           Returns the current record's "Manager" value
 * @method Doctrine_Collection getRiskBuilders()      Returns the current record's "RiskBuilders" collection
 * @method Doctrine_Collection getAccountPlane()      Returns the current record's "AccountPlane" collection
 * @method Doctrine_Collection getUserAccount()       Returns the current record's "UserAccount" collection
 * @method Account             setTitle()             Sets the current record's "title" value
 * @method Account             setPhoto()             Sets the current record's "photo" value
 * @method Account             setChiefPilotEmail()   Sets the current record's "chief_pilot_email" value
 * @method Account             setChiefPilotName()    Sets the current record's "chief_pilot_name" value
 * @method Account             setManagedById()       Sets the current record's "managed_by_id" value
 * @method Account             setPlanes()            Sets the current record's "Planes" collection
 * @method Account             setUsers()             Sets the current record's "Users" collection
 * @method Account             setManager()           Sets the current record's "Manager" value
 * @method Account             setRiskBuilders()      Sets the current record's "RiskBuilders" collection
 * @method Account             setAccountPlane()      Sets the current record's "AccountPlane" collection
 * @method Account             setUserAccount()       Sets the current record's "UserAccount" collection
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account');
        $this->hasColumn('title', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('photo', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('chief_pilot_email', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('chief_pilot_name', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('managed_by_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Plane as Planes', array(
             'refClass' => 'AccountPlane',
             'local' => 'plane_id',
             'foreign' => 'account_id'));

        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'UserAccount',
             'local' => 'user_id',
             'foreign' => 'account_id'));

        $this->hasOne('sfGuardUser as Manager', array(
             'local' => 'managed_by_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('RiskBuilder as RiskBuilders', array(
             'local' => 'id',
             'foreign' => 'account_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('AccountPlane', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $this->hasMany('UserAccount', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}