<?php

/**
 * BaseAirport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $airport_title
 * 
 * @method string  getAirportTitle()  Returns the current record's "airport_title" value
 * @method Airport setAirportTitle()  Sets the current record's "airport_title" value
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAirport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('airport');
        $this->hasColumn('airport_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}