<?php

/**
 * BaseAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $title
 * @property varchar $photo
 * @property varchar $chief_pilot_email
 * @property Doctrine_Collection $Planes
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $AccountPlane
 * @property Doctrine_Collection $UserAccount
 * 
 * @method varchar             getTitle()             Returns the current record's "title" value
 * @method varchar             getPhoto()             Returns the current record's "photo" value
 * @method varchar             getChiefPilotEmail()   Returns the current record's "chief_pilot_email" value
 * @method Doctrine_Collection getPlanes()            Returns the current record's "Planes" collection
 * @method Doctrine_Collection getUsers()             Returns the current record's "Users" collection
 * @method Doctrine_Collection getAccountPlane()      Returns the current record's "AccountPlane" collection
 * @method Doctrine_Collection getUserAccount()       Returns the current record's "UserAccount" collection
 * @method Account             setTitle()             Sets the current record's "title" value
 * @method Account             setPhoto()             Sets the current record's "photo" value
 * @method Account             setChiefPilotEmail()   Sets the current record's "chief_pilot_email" value
 * @method Account             setPlanes()            Sets the current record's "Planes" collection
 * @method Account             setUsers()             Sets the current record's "Users" collection
 * @method Account             setAccountPlane()      Sets the current record's "AccountPlane" collection
 * @method Account             setUserAccount()       Sets the current record's "UserAccount" collection
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account');
        $this->hasColumn('title', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('photo', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('chief_pilot_email', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Plane as Planes', array(
             'refClass' => 'AccountPlane',
             'local' => 'plane_id',
             'foreign' => 'account_id'));

        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'UserAccount',
             'local' => 'user_id',
             'foreign' => 'account_id'));

        $this->hasMany('AccountPlane', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $this->hasMany('UserAccount', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}