<?php

/**
 * BaseRiskFactorField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $risk_builder_id
 * @property string $question
 * @property string $help_mewssage
 * @property integer $position
 * @property RiskBuilder $RiskBuilder
 * @property Doctrine_Collection $RiskFactorField
 * 
 * @method integer             getRiskBuilderId()   Returns the current record's "risk_builder_id" value
 * @method string              getQuestion()        Returns the current record's "question" value
 * @method string              getHelpMewssage()    Returns the current record's "help_mewssage" value
 * @method integer             getPosition()        Returns the current record's "position" value
 * @method RiskBuilder         getRiskBuilder()     Returns the current record's "RiskBuilder" value
 * @method Doctrine_Collection getRiskFactorField() Returns the current record's "RiskFactorField" collection
 * @method RiskFactorField     setRiskBuilderId()   Sets the current record's "risk_builder_id" value
 * @method RiskFactorField     setQuestion()        Sets the current record's "question" value
 * @method RiskFactorField     setHelpMewssage()    Sets the current record's "help_mewssage" value
 * @method RiskFactorField     setPosition()        Sets the current record's "position" value
 * @method RiskFactorField     setRiskBuilder()     Sets the current record's "RiskBuilder" value
 * @method RiskFactorField     setRiskFactorField() Sets the current record's "RiskFactorField" collection
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRiskFactorField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('risk_factor_field');
        $this->hasColumn('risk_builder_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('question', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('help_mewssage', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RiskBuilder', array(
             'local' => 'risk_builder_id',
             'foreign' => 'id'));

        $this->hasMany('ResponseOtionsField as RiskFactorField', array(
             'local' => 'id',
             'foreign' => 'risk_factor_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}