<?php

/**
 * BaseMitigationField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $risk_builder_id
 * @property varchar $type
 * @property varchar $message
 * @property varchar $instructions
 * @property integer $min_value
 * @property integer $max_value
 * @property boolean $chief_notify
 * @property RiskBuilder $RiskBuilder
 * 
 * @method integer         getRiskBuilderId()   Returns the current record's "risk_builder_id" value
 * @method varchar         getType()            Returns the current record's "type" value
 * @method varchar         getMessage()         Returns the current record's "message" value
 * @method varchar         getInstructions()    Returns the current record's "instructions" value
 * @method integer         getMinValue()        Returns the current record's "min_value" value
 * @method integer         getMaxValue()        Returns the current record's "max_value" value
 * @method boolean         getChiefNotify()     Returns the current record's "chief_notify" value
 * @method RiskBuilder     getRiskBuilder()     Returns the current record's "RiskBuilder" value
 * @method MitigationField setRiskBuilderId()   Sets the current record's "risk_builder_id" value
 * @method MitigationField setType()            Sets the current record's "type" value
 * @method MitigationField setMessage()         Sets the current record's "message" value
 * @method MitigationField setInstructions()    Sets the current record's "instructions" value
 * @method MitigationField setMinValue()        Sets the current record's "min_value" value
 * @method MitigationField setMaxValue()        Sets the current record's "max_value" value
 * @method MitigationField setChiefNotify()     Sets the current record's "chief_notify" value
 * @method MitigationField setRiskBuilder()     Sets the current record's "RiskBuilder" value
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMitigationField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mitigation_field');
        $this->hasColumn('risk_builder_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'varchar', 20, array(
             'type' => 'varchar',
             'length' => 20,
             ));
        $this->hasColumn('message', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('instructions', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('min_value', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('max_value', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('chief_notify', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RiskBuilder', array(
             'local' => 'risk_builder_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}