<?php

/**
 * BaseFlightInformationField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $risk_builder_id
 * @property string $information_name
 * @property integer $position
 * @property boolean $hiddable
 * @property RiskBuilder $RiskBuilder
 * 
 * @method integer                getRiskBuilderId()    Returns the current record's "risk_builder_id" value
 * @method string                 getInformationName()  Returns the current record's "information_name" value
 * @method integer                getPosition()         Returns the current record's "position" value
 * @method boolean                getHiddable()         Returns the current record's "hiddable" value
 * @method RiskBuilder            getRiskBuilder()      Returns the current record's "RiskBuilder" value
 * @method FlightInformationField setRiskBuilderId()    Sets the current record's "risk_builder_id" value
 * @method FlightInformationField setInformationName()  Sets the current record's "information_name" value
 * @method FlightInformationField setPosition()         Sets the current record's "position" value
 * @method FlightInformationField setHiddable()         Sets the current record's "hiddable" value
 * @method FlightInformationField setRiskBuilder()      Sets the current record's "RiskBuilder" value
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFlightInformationField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('flight_information_field');
        $this->hasColumn('risk_builder_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('information_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('hiddable', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RiskBuilder', array(
             'local' => 'risk_builder_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}