<?php

/**
 * BaseRiskBuilder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $instructions
 * @property Doctrine_Collection $FlightInformationField
 * @property Doctrine_Collection $MitigationField
 * @property Doctrine_Collection $RiskBuilder
 * 
 * @method string              getName()                   Returns the current record's "name" value
 * @method string              getInstructions()           Returns the current record's "instructions" value
 * @method Doctrine_Collection getFlightInformationField() Returns the current record's "FlightInformationField" collection
 * @method Doctrine_Collection getMitigationField()        Returns the current record's "MitigationField" collection
 * @method Doctrine_Collection getRiskBuilder()            Returns the current record's "RiskBuilder" collection
 * @method RiskBuilder         setName()                   Sets the current record's "name" value
 * @method RiskBuilder         setInstructions()           Sets the current record's "instructions" value
 * @method RiskBuilder         setFlightInformationField() Sets the current record's "FlightInformationField" collection
 * @method RiskBuilder         setMitigationField()        Sets the current record's "MitigationField" collection
 * @method RiskBuilder         setRiskBuilder()            Sets the current record's "RiskBuilder" collection
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRiskBuilder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('risk_builder');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('instructions', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FlightInformationField', array(
             'local' => 'id',
             'foreign' => 'risk_builder_id'));

        $this->hasMany('MitigationField', array(
             'local' => 'id',
             'foreign' => 'risk_builder_id'));

        $this->hasMany('RiskFactorField as RiskBuilder', array(
             'local' => 'id',
             'foreign' => 'risk_builder_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}