<?php

/**
 * BaseAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $title
 * @property varchar $photo
 * @property integer $managed_by_id
 * @property integer $chief_pilot_id
 * @property boolean $has_modified_form
 * @property boolean $has_plane
 * @property boolean $has_pilot
 * @property boolean $has_skipped_pilot
 * @property boolean $has_flight
 * @property boolean $is_active
 * @property Doctrine_Collection $Planes
 * @property Doctrine_Collection $Users
 * @property sfGuardUser $ChiefPilot
 * @property sfGuardUser $Manager
 * @property Doctrine_Collection $RiskBuilders
 * @property Doctrine_Collection $AccountPlane
 * @property Doctrine_Collection $UserAccount
 * @property Doctrine_Collection $Flight
 * 
 * @method varchar             getTitle()             Returns the current record's "title" value
 * @method varchar             getPhoto()             Returns the current record's "photo" value
 * @method integer             getManagedById()       Returns the current record's "managed_by_id" value
 * @method integer             getChiefPilotId()      Returns the current record's "chief_pilot_id" value
 * @method boolean             getHasModifiedForm()   Returns the current record's "has_modified_form" value
 * @method boolean             getHasPlane()          Returns the current record's "has_plane" value
 * @method boolean             getHasPilot()          Returns the current record's "has_pilot" value
 * @method boolean             getHasSkippedPilot()   Returns the current record's "has_skipped_pilot" value
 * @method boolean             getHasFlight()         Returns the current record's "has_flight" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method Doctrine_Collection getPlanes()            Returns the current record's "Planes" collection
 * @method Doctrine_Collection getUsers()             Returns the current record's "Users" collection
 * @method sfGuardUser         getChiefPilot()        Returns the current record's "ChiefPilot" value
 * @method sfGuardUser         getManager()           Returns the current record's "Manager" value
 * @method Doctrine_Collection getRiskBuilders()      Returns the current record's "RiskBuilders" collection
 * @method Doctrine_Collection getAccountPlane()      Returns the current record's "AccountPlane" collection
 * @method Doctrine_Collection getUserAccount()       Returns the current record's "UserAccount" collection
 * @method Doctrine_Collection getFlight()            Returns the current record's "Flight" collection
 * @method Account             setTitle()             Sets the current record's "title" value
 * @method Account             setPhoto()             Sets the current record's "photo" value
 * @method Account             setManagedById()       Sets the current record's "managed_by_id" value
 * @method Account             setChiefPilotId()      Sets the current record's "chief_pilot_id" value
 * @method Account             setHasModifiedForm()   Sets the current record's "has_modified_form" value
 * @method Account             setHasPlane()          Sets the current record's "has_plane" value
 * @method Account             setHasPilot()          Sets the current record's "has_pilot" value
 * @method Account             setHasSkippedPilot()   Sets the current record's "has_skipped_pilot" value
 * @method Account             setHasFlight()         Sets the current record's "has_flight" value
 * @method Account             setIsActive()          Sets the current record's "is_active" value
 * @method Account             setPlanes()            Sets the current record's "Planes" collection
 * @method Account             setUsers()             Sets the current record's "Users" collection
 * @method Account             setChiefPilot()        Sets the current record's "ChiefPilot" value
 * @method Account             setManager()           Sets the current record's "Manager" value
 * @method Account             setRiskBuilders()      Sets the current record's "RiskBuilders" collection
 * @method Account             setAccountPlane()      Sets the current record's "AccountPlane" collection
 * @method Account             setUserAccount()       Sets the current record's "UserAccount" collection
 * @method Account             setFlight()            Sets the current record's "Flight" collection
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account');
        $this->hasColumn('title', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('photo', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('managed_by_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('chief_pilot_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('has_modified_form', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('has_plane', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('has_pilot', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('has_skipped_pilot', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('has_flight', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Plane as Planes', array(
             'refClass' => 'AccountPlane',
             'local' => 'plane_id',
             'foreign' => 'account_id'));

        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'UserAccount',
             'local' => 'user_id',
             'foreign' => 'account_id'));

        $this->hasOne('sfGuardUser as ChiefPilot', array(
             'local' => 'chief_pilot_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser as Manager', array(
             'local' => 'managed_by_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('RiskBuilder as RiskBuilders', array(
             'local' => 'id',
             'foreign' => 'account_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('AccountPlane', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $this->hasMany('UserAccount', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $this->hasMany('Flight', array(
             'local' => 'id',
             'foreign' => 'account_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}