<?php

/**
 * BaseAccountPlane
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $account_id
 * @property integer $plane_id
 * @property Account $Account
 * @property Plane $Plane
 * 
 * @method integer      getAccountId()  Returns the current record's "account_id" value
 * @method integer      getPlaneId()    Returns the current record's "plane_id" value
 * @method Account      getAccount()    Returns the current record's "Account" value
 * @method Plane        getPlane()      Returns the current record's "Plane" value
 * @method AccountPlane setAccountId()  Sets the current record's "account_id" value
 * @method AccountPlane setPlaneId()    Sets the current record's "plane_id" value
 * @method AccountPlane setAccount()    Sets the current record's "Account" value
 * @method AccountPlane setPlane()      Sets the current record's "Plane" value
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccountPlane extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account_plane');
        $this->hasColumn('account_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('plane_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Account', array(
             'local' => 'account_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Plane', array(
             'local' => 'plane_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}