sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               users
    prefix_path:          /admin/users
    column:               id
    with_wildcard_routes: true


forgot_password:
  url: /admin/forgot_password
  param: { module: registration, action: forgotPassword }

signin_process:
  url: /admin/signin/process
  param: { module: registration, action: processSignin }

signin:
  url: /admin/signin
  param: { module: registration, action: signin }

signout:
  url: /admin/signout
  param: { module: registration, action: signout }

signup_check:
  url: /admin/signup/check
  param: { module: registration, action: signupCheck }

signup_invite:
  url: /admin/signup/:token
  param: { module: registration, action: signup }

signup:
  url: /admin/signup
  param: { module: registration, action: signup }

account:
  class: sfDoctrineRouteCollection
  options:
    model:                Account
    module:               account
    prefix_path:          /admin/accounts
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /admin
  param: { module: sfAdminDash, action: dashboard }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
