<?php

/**
 * AccountPlaneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountPlaneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountPlaneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountPlane');
    }
}