<?php

/**
 * AirportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AirportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AirportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Airport');
    }
}