<?php

/**
 * FlightInformationFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FlightInformationFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FlightInformationFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FlightInformationField');
    }
}