<?php

/**
 * MitigationFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MitigationFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MitigationFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MitigationField');
    }
}