<?php

/**
 * PlaneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlaneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plane');
    }

    public static function getPlanesByAccount($account_id){
        return Doctrine_Query::create()
            ->from("Plane p")
            ->leftJoin('p.AccountPlane ap')
            ->where('ap.account_id = ?', $account_id)
            ->orderBy('p.position')
            ->execute();
    }

    public static function getMaxPosition($account_id){
        $query = Doctrine_Query::create()
            ->select('MAX(p.position) as max_position')
            ->from('Plane p')
            ->leftJoin('p.AccountPlane ap')
            ->where('ap.account_id = ?', $account_id)
            ->fetchOne();
        $max_position = $query->getMaxPosition();
        return $max_position ? $max_position : 0;
    }
}