<?php

/**
 * PlaneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlaneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plane');
    }

    public static function getPlanesByAccount($account_id){
        return Doctrine_Query::create()
            ->from("Plane p")
            ->leftJoin('p.AccountPlane ap')
            ->where('ap.account_id = ?', $account_id)
            ->execute();
    }
}