<?php

/**
 * ResponseOtionsFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResponseOtionsFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResponseOtionsFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResponseOtionsField');
    }
}