<?php

/**
 * ResponseOptionFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResponseOptionFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResponseOptionFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResponseOptionField');
    }
}