<?php

/**
 * ResponseOptionFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResponseOptionFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResponseOptionFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResponseOptionField');
    }

    public static function getResponsesCountByRiskFactor($risk_factor_id){
        return Doctrine_Query::create()
            ->select('count(*) as responses_count')
            ->from('ResponseOptionField rof')
            ->where('rof.risk_factor_id = ?', $risk_factor_id)
            ->fetchOne()
            ->getResponsesCount();
    }
}