<?php

/**
 * RiskBuilderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RiskBuilderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RiskBuilderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RiskBuilder');
    }
}