<?php

/**
 * RiskFactorFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RiskFactorFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RiskFactorFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RiskFactorField');
    }
}