<?php

/**
 * RiskBuilderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RiskBuilderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RiskBuilderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RiskBuilder');
    }

    public static function getLatePosition($risk_builder_id)
    {
        $query = Doctrine_Query::create()
            ->select("max(position)")
            ->from('RiskFactorField')
            ->where("risk_builder_id = ?", $risk_builder_id)
            ->execute(array(), Doctrine::HYDRATE_SINGLE_SCALAR);

        return $query;
    }
}