<?php

/**
 * UserAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserAccountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserAccount');
    }
}