# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:

  sf_captchagd:
    image_width:                100
    image_height:               30
    chars:                      "123456789"
    length:                     4
    font_size:                  18
    force_new_captcha:          true

    # possible chars colors
    font_color:                 ["252525", "8b8787", "550707", "3526E6", "88531E"]

    # chars fonts
    fonts:                      ["akbar/akbar.ttf", "brushcut/BRUSHCUT.TTF", "molten/molten.ttf", "planet_benson/Planetbe.ttf", "whoobub/WHOOBUB_.TTF"]
    background_color:           DDDDDD
    border_color:               000000


  email_notification:
    from_name: 'Pre Flight Risk'
    from_email: 'support@preflightrisk.com'
    title: 'Invite to PreFlightRisk'
    message: "You have ben registered in Blueprint project.\n\rYour password is %password%\n\rPlease use this link to activate your accout - %activation_link%\n\r"

  email_assessment:
    from_name: 'Pre Flight Risk'
    from_email: 'themitigators@preflightrisk.com'


  mailchimp:
    api_key: '2689d6347e49faced7add6121db8a86b-us5'
    news_feed: 'd046cd6a1a'
    weekly_news_feed: '6164040c73'
    monthly_news_feed: '8448c32b1c'

  mandrill:
    api_key: 'Yv1t_hEvBEXYuT1vlY9YDg'

  password:
    change_title: 'Password change'
    reset_title:  'Password recovery'

  error_notification:
    error_title:  'The Solution - Internal Server Error'

  password_notification:
    title: "Password change notification"
    message: "You have successfully changed your password in Blueprint project.\n\rYour new password is: %password%\n\r"

  page:
    comment_count: 10

  news:
    comment_count: 10

  dashboard:
    limit: 10
    chart:
      risk:
        metric: "Risk"
        color:  "#00AEEF"
      mitigation:
        metric: "Mitigation"
        color:  "#16CB3F"


  tiny_mce:
    my_settings_content:
      relative_urls: true,
      remove_script_host: false,
      skin: "o2k7",
      height: '200',
      width: '842',
      dialog_type: "modal",
      relative_urls: false,
      plugins: "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
      theme_advanced_buttons1: "bold,italic,underline,strikethrough,forecolor,formatselect,bullist,numlist,blockquote,undo,redo,link,unlink,image,sub,sup,charmap,fullscreen,code",
      theme_advanced_buttons1_add: "",
      theme_advanced_buttons2: "",
      theme_advanced_buttons3: "",
      theme_advanced_buttons4: "",
      theme_advanced_toolbar_location: "top",
      theme_advanced_toolbar_align: "center",
      theme_advanced_statusbar_location: "none",
      theme_advanced_resizing: false,
      paste_auto_cleanup_on_paste: true,
      theme: "advanced",
      file_browser_callback: "tinyBrowser",
      content_css : "",
      convert_urls : false

  photo:
    image_size:
      height: 100
      width: 100

  sf_admin_dash:
    web_dir:                      /sfAdminDashPlugin
    image_dir:                    /sfAdminDashPlugin/images/icons/
    default_image:                config.png
    resize_mode:                  thumbnail
    site:                         "The Solution - Admin panel"
    include_path:                 true
    include_jquery_no_conflict:   false
    logout:                       true
    login_route:                  @sf_guard_signin
    logout_route:                 @sf_guard_signout

  sf_admin_dash:
    categories:
#      Users:
#        items:
#          Users Management:
#            url:          users
#            image:        users.png
#            credentials:  [superadmin]
      Title:
        items:

          Book:
            url:          book_admin
            image:        addedit.png
            credentials:  [superadmin]
          News:
            url:          news_admin
            image:        addedit.png
            credentials:  [superadmin]

  facebook:
    app_id: 182001591950448
    app_secret: 068781ad90dcd0edc8df4353d27345a6

