update_risk_factor:
  url: /form/update-risk-factor
  param: { module: builder, action: updateRiskFactor }

save_risk_factor:
  url: /form/save-risk-factor
  param: { module: builder, action: saveRiskFactor }

edit_risk_factor_field:
  url: /form/edit-new-risk-factor-field
  param: { module: builder, action: editRiskFactorField }


add_new_response_option_field:
  url: /form/add-new-response-option-field
  param: { module: builder, action: addNewResponseOptionField }

add_new_risk_factor_field:
  url: /form/add-new-risk-factor-field
  param: { module: builder, action: addNewRiskFactorField }

save_flight_info_position:
  url: /form/save-flight-info-position
  param: { module: builder, action: saveFlightInfoPosition }

save_form_field_hidding:
  url: /form/save-form-field-hidding
  param: { module: builder, action: saveFormFieldHidding }

save_mitigation_range:
  url: /form/save-mitigation-range
  param: { module: builder, action: saveMitigationRange }

save_mitigation_section:
  url: /form/save-mitigation-section
  param: { module: builder, action: saveMitigationSection }

cancel_mitigation_section:
  url: /form/cancel-mitigation-section
  param: { module: builder, action: cancelMitigationSection }

form:
  url: /form
  param: { module: builder, action: index }


homepage:
  url: /
  param: { module: home, action: index }

