save_flight_info_position:
  url: /form/save-flight-info-position
  param: { module: builder, action: saveFlightInfoPosition }

save_form_field_hidding:
  url: /form/save-form-field-hidding
  param: { module: builder, action: saveFormFieldHidding }

save_mitigation_range:
  url: /form/save-mitigation-range
  param: { module: builder, action: saveMitigationRange }

save_mitigation_section:
  url: /form/save-mitigation-section
  param: { module: builder, action: saveMitigationSection }

cancel_mitigation_section:
  url: /form/cancel-mitigation-section
  param: { module: builder, action: cancelMitigationSection }

form:
  url: /form
  param: { module: builder, action: index }


homepage:
  url: /
  param: { module: home, action: index }

