dashboard:
  url: /:account_id/dashboard
  param: { module: dashboard, action: index }
  requirements:
    account_id: \d+
    

update_pilot:
  url: /settings/update-pilot
  param: { module: settings, action: updatePilot}

save_pilot:
  url: /settings/save-pilot
  param: { module: settings, action: savePilot }

delete_pilot:
  url: /settings/delete-pilot
  param: { module: settings, action: deletePilot }

edit_pilot:
  url: /settings/edit-pilot
  param: { module: settings, action: editPilotField }

add_new_pilot_field:
  url: /settings/add-new-pilot-field
  param: { module: settings, action: addNewPilotField }

save_pilot_position:
  url: /settings/save-pilot-position
  param: { module: settings, action: savePilotPosition }
      

update_plane:
  url: /settings/update-plane
  param: { module: settings, action: updatePlane}

save_plane:
  url: /settings/save-plane
  param: { module: settings, action: savePlane }

delete_plane:
  url: /settings/delete-plane
  param: { module: settings, action: deletePlane }

edit_plane:
  url: /settings/edit-plane
  param: { module: settings, action: editPlaneField }

add_new_plane_field:
  url: /settings/add-new-plane-field
  param: { module: settings, action: addNewPlaneField }

save_plane_position:
  url: /settings/save-plane-position
  param: { module: settings, action: savePlanePosition }


process_account_information_data:
  url: /:account_id/settings/process-account-data
  param: { module: settings, action: processAccountData }
  requirements:
    account_id: \d+

process_my_information_data:
  url: /:account_id/settings/process-my-information-data
  param: { module: settings, action: processMyInformationData }
  requirements:
    account_id: \d+

my_information_upload_avatar:
  url: /settings/information/upload-avatar
  param: { module: settings, action: uploadAvatar }

my_information_crop_image:
  url: /settings/information/crop-image
  param: { module: settings, action: cropImage }

settings:
  url: /:account_id/settings
  param: { module: settings, action: index }
  requirements:
    account_id: \d+




update_risk_factor:
  url: /form/update-risk-factor
  param: { module: builder, action: updateRiskFactor }

save_risk_factor:
  url: /form/save-risk-factor
  param: { module: builder, action: saveRiskFactor }

delete_risk_factor:
  url: /form/delete-risk-factor
  param: { module: builder, action: deleteRiskFactor }

edit_risk_factor_field:
  url: /form/edit-new-risk-factor-field
  param: { module: builder, action: editRiskFactorField }

add_new_response_option_field:
  url: /form/add-new-response-option-field
  param: { module: builder, action: addNewResponseOptionField }

delete_response_option:
  url: /form/delete-response-option
  param: { module: builder, action: deleteResponseOption }

add_new_risk_factor_field:
  url: /form/add-new-risk-factor-field
  param: { module: builder, action: addNewRiskFactorField }

save_risk_factor_position:
  url: /form/save-risk-factor-position
  param: { module: builder, action: saveRiskFactorPosition }

show_hide_field:
  url: /form/show-hide-field
  param: { module: builder, action: showHideField }

save_flight_info_position:
  url: /form/save-flight-info-position
  param: { module: builder, action: saveFlightInfoPosition }

save_form_field_hidding:
  url: /form/save-form-field-hidding
  param: { module: builder, action: saveFormFieldHidding }

save_mitigation_range:
  url: /form/save-mitigation-range
  param: { module: builder, action: saveMitigationRange }

save_mitigation_section:
  url: /form/save-mitigation-section
  param: { module: builder, action: saveMitigationSection }

cancel_mitigation_section:
  url: /form/cancel-mitigation-section
  param: { module: builder, action: cancelMitigationSection }

form:
  url: /form
  param: { module: builder, action: index }


create_account_upload_avatar:
  url: /new/account/upload-avatar
  param: { module: registration, action: uploadAvatar }

create_account_crop_image:
  url: /new/account/crop-image
  param: { module: registration, action: cropImage }

select_account:
  url: /select
  param: { module: registration, action: selectAccount }


create_account:
  url: /new/account
  param: { module: registration, action: createAccount }


signin_process:
  url: /signin/process
  param: { module: registration, action: processSignin }

signin:
  url: /signin
  param: { module: registration, action: signin }

signout:
  url: /signout
  param: { module: registration, action: signout }

signup_invite:
  url: /signup/:token
  param: { module: registration, action: signup }

signup:
  url: /signup
  param: { module: registration, action: signup }

homepage:
  url: /
  param: { module: home, action: index }

