# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  default_culture:   en
  culture:           en
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            0ef5c9ad624daeb8729f2fe03d5d63f2f0d87050

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    enabled_modules:      [default, sfGuardAuth, sfCaptchaGD, sfThumbnail, sfAdminDash]

    login_module:         registration
    login_action:         signin

    standard_helpers:     [Partial, Cache, I18N, Captcha]

    i18n:                 true
    #default_culture:      ru_RU
    #culture:              ru

  .actions:
    #page not found
    error_404_module:       errors     # module "errors"
    error_404_action:       error404   # action "executeError404"
    #403 credential required
    secure_module:          errors     # module "errors"
    secure_action:          error403   # action "executeError403"

