# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [style.css, jquery.fancybox.css]

  javascripts:    [/js/tiny_mce/plugins/tinybrowser/tb_tinymce.js.php, jquery-1.8.3.js, jquery-ui-1.8.22.custom.min.js, /js/noty/jquery.noty.js, /js/noty/layouts/top.js, /js/noty/themes/default.js, /js/jquery.maskedinput.js, /js/jquery.fancybox.js]

  has_layout:     true
  layout:         layout

dashboardSuccess:
  has_layout:     true
  layout:         layout_dash
