<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    public static function getUserByCode($code)
    {
        $q = Doctrine_Query::create()
             ->select("user.*")
             ->from("sfGuardUser user, ActivationCode code")
             ->where("(user.id = code.user_id) AND (code.code = '$code')");

        return $q->fetchOne();
    }

    public static function existsVkUser($user_id){
        $user = self::getInstance()->findOneBy('vk_id', $user_id);
        return $user ? $user : false;
    }

    public static function existsFbUser($id){
        $user = self::getInstance()->findOneBy('facebook_id', $id);
        return $user ? $user : false;
    }

    public static function existEmail($email)
    {
        $user = self::getInstance()->findOneBy('email_address', $email);
        return $user ? $user : false;
    }

    public static function checkUserByUsername($username){
        $user = Doctrine_Query::create()
            ->from("sfGuardUser u")
            ->where("u.username LIKE ?", $username)
            ->fetchOne();
        return !$user ? true : false;
    }

    public static function checkUserByNick($nick){
        $user = Doctrine_Query::create()
            ->from("sfGuardUser u")
            ->where("u.nick LIKE ?", $nick)
            ->fetchOne();
        return !$user ? true : false;
    }
}