<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('user_account', 'is_pic');
        $this->removeColumn('user_account', 'is_sic');
        $this->addColumn('user_account', 'role', 'enum', '', array(
             'values' => 
             array(
              0 => 'pic',
              1 => 'sic',
              2 => 'both',
             ),
             'default' => 'both',
             ));
    }

    public function down()
    {
        $this->addColumn('user_account', 'is_pic', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('user_account', 'is_sic', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->removeColumn('user_account', 'role');
    }
}