<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('risk_builder', 'mitigation_low_email', 'string', '255', array(
             ));
        $this->addColumn('risk_builder', 'mitigation_medium_email', 'string', '255', array(
             ));
        $this->addColumn('risk_builder', 'mitigation_high_email', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('risk_builder', 'mitigation_low_email');
        $this->removeColumn('risk_builder', 'mitigation_medium_email');
        $this->removeColumn('risk_builder', 'mitigation_high_email');
    }
}