<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('flight_information_field', 'is_required', 'boolean', '25', array(
            'default' => '0',
        ));

        $this->addColumn('flight_information_field', 'required', 'boolean', '25', array(
            'default' => '1',
        ));
    }

    public function down()
    {
        $this->removeColumn('flight_information_field', 'is_required');

        $this->removeColumn('flight_information_field', 'required');
    }
}