<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('account_plane', 'account_plane_plane_id_account_id', array(
             'name' => 'account_plane_plane_id_account_id',
             'local' => 'plane_id',
             'foreign' => 'id',
             'foreignTable' => 'account',
             ));
        $this->createForeignKey('user_account', 'user_account_user_id_account_id', array(
             'name' => 'user_account_user_id_account_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'account',
             ));
        $this->addIndex('account_plane', 'account_plane_plane_id', array(
             'fields' => 
             array(
              0 => 'plane_id',
             ),
             ));
        $this->addIndex('user_account', 'user_account_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('account_plane', 'account_plane_plane_id_account_id');
        $this->dropForeignKey('user_account', 'user_account_user_id_account_id');
        $this->removeIndex('account_plane', 'account_plane_plane_id', array(
             'fields' => 
             array(
              0 => 'plane_id',
             ),
             ));
        $this->removeIndex('user_account', 'user_account_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}