<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user_account', 'is_pic', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('user_account', 'is_sic', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('user_account', 'is_pic');
        $this->removeColumn('user_account', 'is_sic');
    }
}