<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('flight', 'time_str', 'varchar', '20', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('flight', 'time_str');
    }
}