<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('risk_builder', 'high_risk_factor_notify', 'boolean', '25', array(
             'default' => '1',
             ));
        $this->addColumn('risk_builder', 'high_risk_factor_email', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('risk_builder', 'high_risk_factor_notify');
        $this->removeColumn('risk_builder', 'high_risk_factor_email');
    }
}