RiskBuilder:
  actAs: [Timestampable]
  columns:
    form_name:                     {type: string(255)}
    form_instructions:             {type: string(255)}
    mitigation_low_message:        {type: string(255)}
    mitigation_low_instructions:   {type: string(255)}
    mitigation_low_min:            {type: integer, default: 0 }
    mitigation_low_max:            {type: integer, default: 14 }
    mitigation_low_notify:         {type: boolean, default: true}
    mitigation_medium_message:     {type: string(255)}
    mitigation_medium_instructions: {type: string(255)}
    mitigation_medium_min:         {type: integer, default: 15 }
    mitigation_medium_max:         {type: integer, default: 24 }
    mitigation_medium_notify:      {type: boolean, default: true}
    mitigation_medium_require_details:      {type: boolean, default: true}
    mitigation_high_message:       {type: string(255)}
    mitigation_high_instructions:   {type: string(255)}
    mitigation_high_min:           {type: integer, default: 25 }
    mitigation_high_max:           {type: integer, default: 50 }
    mitigation_high_notify:        {type: boolean, default: true}
    mitigation_high_prevent_flight:        {type: boolean, default: true}

  relations:
    RiskFactorFields:
      class: RiskFactorField
      local: id
      foreign: risk_builder_id
      type: many
    FlightInformationFields:
      class: FlightInformationField
      local: id
      foreign: risk_builder_id
      type: many


RiskFactorField:
  actAs: [Timestampable]
  columns:
    risk_builder_id:          {type: integer}
    question:         {type: string(255)}
    help_message:    {type: string(255)}
    position:         {type: integer}
  relations:
    RiskBuilder:
      class: RiskBuilder
      local: risk_builder_id
      foreign: id
      type: one
    ResponseOptions:
      class: ResponseOptionField
      local: id
      foreign: risk_factor_id
      type: many

ResponseOptionField:
  actAs: [Timestampable]
  columns:
    risk_factor_id:   {type: integer}
    response_text:    {type: string(255)}
    response_value:   {type: integer}
    note:             {type: string(255)}
  relations:
    RiskFactorField:
      class: RiskFactorField
      local: risk_factor_id
      foreign: id
      type: one

FlightInformationField:
  actAs: [Timestampable]
  columns:
    risk_builder_id:          {type: integer}
    information_name: {type: string(255)}
    position:         {type: integer}
    hiddable:         {type: boolean}
    is_hide:          {type: boolean, default: false}
  relations:
    RiskBuilder:
      class: RiskBuilder
      local: risk_builder_id
      foreign: id
      type: one

MitigationField:
  actAs: [Timestampable]
  columns:
    risk_builder_id:          {type: integer}
    type:             {type: varchar(20)}
    message:          {type: varchar(255)}
    instructions:     {type: varchar(255)}
    min_value:        {type: integer}
    max_value:        {type: integer}
    chief_notify:     {type: boolean}
  relations:
    RiskBuilder:
      foreignAlias: RiskBuilder
      local: risk_builder_id
      foreign: id
      type: one
      foreignType: many

