all:
  stylesheets: [jquery.ui.selectmenu.css, print.css]
  javascripts: [jquery.form.js, jquery.validate.js, jquery.ui.core.js, jquery.ui.widget.js, jquery.ui.position.js, jquery.ui.selectmenu.js, jquery.PrintArea.js]